### ISSUE TITLE
change permissions of newly created volumes to uid:gid

### ISSUE THREAD

**Issue by s4ke** [costela/docker-volume-hetzner#18]
Hey there,

I was wondering if it was possible in concept to automatically chown a newly created volumes to a specific user. While generally being awesome, we have to change containers to run as root sometimes just to automatically be able to create folder structures.

If you think it is generally possible, I'd be happy to send a PR your way :)

**Comment by costela** [comment]
Hi,

I think this should be relatively trivial, by just adding another option and [chowning after mounting](https://github.com/costela/docker-volume-hetzner/blob/62581aee9ef971c7f40e0cccdd110dc1e0ec9769/driver.go#L95).

This would have the same caveats as the `fstype` option though, so it would only work for new volumes.

Probably enough?

**Comment by s4ke** [comment]
Yeah, this only working for new volumes would be totally enough for us and would probably be the safest way to implement this anyways.

I will try to come up with a PR for this :)
