### ISSUE TITLE
arm64 version

### ISSUE THREAD

**Issue by s4ke** [costela/docker-volume-hetzner#42]
As Hetzner has arm64 instances, it would be great if we could add arm64 to CSI here.

more info here https://github.com/hetznercloud/csi-driver/issues/428 (Hetzner CSI driver in beta)

**Comment by s4ke** [comment]
@costela looking at the github workflow, it looks like the releases are done by hand, so I can't contribute much besides the Dockerfile / Makefile change, but if you want I can do that already

**Comment by s4ke** [comment]
@costela can you create a release with the latest changes so that the build gets triggered?

**Comment by costela** [comment]
done :heavy_check_mark:
