### ISSUE TITLE
Error during docker-compose start: VolumeDriver.Mount: could not attach volume

### ISSUE THREAD

**Issue by hnk** [costela/docker-volume-hetzner#8]
Hi there,

I wanted to use your plugin, but when I run a docker-compose setup, I get the following error:

`ERROR: for web  Cannot start service web: error while mounting volume '/var/lib/docker/plugins/******/propagated-mount/******': VolumeDriver.Mount: could not attach volume 'docker-nextcloud-dockerized_nextcloud' to 'cloud': cannot perform operation because server is locked (locked)`

I think this happens because I have two services defined that access the same volume, though one mounts it read-only.

The set-up is the exact nextcloud docker-compose setup: https://github.com/nextcloud/docker/blob/master/.examples/docker-compose/with-nginx-proxy/mariadb-cron-redis/fpm/docker-compose.yml

Could you support me in getting this to work?

**Comment by hnk** [comment]
I just read something in your readme:
> [...] This also precludes concurrent use by multiple containers on the same node [...]
Does this apply to my setup as well? I am not using docker swarm, just on a single machine.

**Comment by costela** [comment]
Yes, usage from multiple services is currently not supported (mostly a docker limitation).

The error you reported seems to indicate a different problem though :thinking:   
Regardless, even if this is fixed, the underlying problem persists: it's currently not possible to use the same volume from different services, and judging by docker's history, it probably won't ever be :/
